tap "asmvik/formulae"

brew "antigen"
brew "chezmoi"
brew "duti"
brew "fswatch"
brew "asmvik/formulae/yabai"
brew "asmvik/formulae/skhd"
brew "jq"
brew "mise"
brew "neovim"
brew "starship"
brew "tmux"
brew "sesh"
brew "yazi"
brew "zoxide"
brew "fzf"
brew "terminal-notifier"

cask "ghostty"
cask "karabiner-elements"
