#!/usr/bin/env bash

set -euo pipefail

module_dir="${0%/*}"

open -n -a Ghostty --args \
  --title="scratchpad:dev_space_prompt" \
  --working-directory="$HOME" \
  --background=#000000 \
  --background-opacity=1 \
  --background-blur=false \
  --command="direct:$module_dir/spotlight-zsh"
