#!/usr/bin/env bash

set -euo pipefail

module_dir="${0%/*}"

open -n -a Ghostty --args \
  --title="scratchpad:dev_space_prompt" \
  --working-directory="$HOME" \
  --command="direct:$module_dir/spotlight-zsh"
